### ISSUE TITLE
Erro ao instalar a partir da Microsoft Store

### ISSUE THREAD

**Issue by willvianna** [azurejoga/Aurora-Windows-Optimizer#15]
Olá, ao tentar instalar o aurora, apenas da erro na instalação e nenhuma mensagem a mais, fica apenas carregando.
![Captura de Tela (1)](https://github.com/user-attachments/assets/bec751bb-c743-459f-bc47-88e9784438b3)

**Comment by azurejoga** [comment]
olá @willvianna  
Você já tentou realizar os seguintes passos?
1. aperte windows + R e digite no executar do windows
2. wsreset.exe
3. Talvez o problema esteja em sua microsoft store, aparentemente a instalação correu bem para mim.
4. Peça para outras pessoas testarem e se caso ouver problema na instalação com elas também, favor comentar aqui no issue.
Agradeço!
Estou investigando

**Comment by edu-mx** [comment]
Olá @willvianna!
Por aqui tá tudo funcionando normal.
Assim que clico para instalar e finaliza... O ícone aparece na área de trabalho.

**Comment by azurejoga** [comment]
problema fechado devido a ser um bug do próprio usuário com sua microsoft store
