### ISSUE TITLE
Tradução da documentação arquivo aurora.py

### ISSUE THREAD

**Issue by Maracujacake** [azurejoga/Aurora-Windows-Optimizer#5]
Em vista de possibilitar que pessoas que não entendem português também possam contribuir para o projeto ou ao menos entendê-lo melhor, sugiro que haja uma tradução da documentação do arquivo aurora.py, assim como o arquivo ''aurora-otimizar.ps1'' encontra-se com comentários em inglês. 

Tomei a iniciativa para fazê-lo, porém ainda está sujeito à revisão: https://replit.com/join/myryrczcbj-madlordx

**Comment by azurejoga** [comment]
Olá @Maracujacake  tudo bem?
Criei uma pasta no repositório chamada [translations](https://github.com/azurejoga/Aurora-Windows-Optimizer/commit/15db02c124e0c31f803a6d4f03da67029589f553)

E lá estão os arquivos de tradução em, /locale, espanhol e inglês.. .po, que logo serão compilados para .mo

Também, o script aurora-english.py que você  traduziu que foi revisado por mim.
Se por acaso quiser fazer alguma alteração, favor fazer um fork do reppo e criar uma branch e depois commitar pedindo para mesclar com o repositório principal! obrigado!

Caso queira traduzir os arquivos, faça diretamente do diretório que logicamente será revisado por mim depois.

Obrigado pela sua contribuição! estamos planejando -breve, talvez na nova versão adicionar suporte a outros idiomas. 
😊👏🌅
Não consegui achar o script aurora-otimizar.ps1 que você traduziu. só achei o código fonte.

**Comment by azurejoga** [comment]
Fechado!
